version: '3.8'

services:
  postgres:
    image: postgres:15
    container_name: job-diary-postgres
    network_mode: host
    environment:
      POSTGRES_DB: job_diary
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: password
    volumes:
      - postgres_data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 5s
      timeout: 5s
      retries: 5

volumes:
  postgres_data: