import React from 'react';
import Provider from '@/provider';

export const metadata = {
  title: '日記',
  description: 'Generated by create next app',
  themeColor: '#ffffff',
};

export default async function RootLayout({ children }: { children: React.ReactNode }) {
  return (
    <html lang="ja">
      <head />
      <body>
        <Provider>{children}</Provider>
      </body>
    </html>
  );
}
