version: '3'
services:
  job-dialy:
    build:
      dockerfile: ./Dockerfile
    image: job-dialy
    ports:
      - 3000:3000
    environment:
      DATABASE_URL: mysql://root:root@host.docker.internal:3306/job-dialy
    env_file:
      - .env.local
  db:
    image: mysql:8
    restart: always
    ports:
      - '3306:3306'
    volumes:
      - 'db:/var/lib/mysql'
    environment:
      MYSQL_ROOT_PASSWORD: 'root'

volumes:
  db:
